import type { Language } from './i18n'

export const agentHistoryCopy = {
  en: { history: 'History', conversations: 'Conversations', orders: 'Wallet orders', empty: 'Your conversations will appear here.', noOrders: 'No orders in this wallet yet.', saved: 'Saved on this device. Each wallet has its own history.', unsaved: 'History could not be saved on this device.', remove: 'Delete conversation', current: 'Current conversation',
    auditConsent: 'I understand Binance has no security audit for this token. I have reviewed the contract and trade.', refreshed: 'Refresh research', savedResearch: 'Saved research · refresh for current data',
    filled: 'Filled', failed: 'Failed', expired: 'Expired', cancelled: 'Cancelled', pending: 'Awaiting fill', confirming: 'Verifying settlement', buy: 'Buy', sell: 'Sell', estimated: 'Estimated receive', received: 'Received', missing: 'Amount unavailable' },
  zh: { history: '历史', conversations: '对话', orders: '钱包订单', empty: '你的对话将显示在这里。', noOrders: '此钱包暂无订单。', saved: '保存在此设备，每个钱包有独立的历史。', unsaved: '无法在此设备保存历史。', remove: '删除对话', current: '当前对话',
    auditConsent: '我了解 Binance 未对此代币提供安全审计，并已审核合约和交易。', refreshed: '刷新研究', savedResearch: '已保存的研究 · 请刷新以获取当前数据',
    filled: '已成交', failed: '失败', expired: '已过期', cancelled: '已取消', pending: '等待成交', confirming: '核实结算中', buy: '买入', sell: '卖出', estimated: '预计收到', received: '已收到', missing: '数量暂无数据' },
  es: { history: 'Historial', conversations: 'Conversaciones', orders: 'Órdenes de la cartera', empty: 'Tus conversaciones aparecerán aquí.', noOrders: 'Esta cartera aún no tiene órdenes.', saved: 'Guardado en este dispositivo. Cada cartera tiene su historial.', unsaved: 'No se pudo guardar el historial en este dispositivo.', remove: 'Eliminar conversación', current: 'Conversación actual',
    auditConsent: 'Entiendo que Binance no tiene una auditoría de seguridad para este token. He revisado el contrato y la operación.', refreshed: 'Actualizar investigación', savedResearch: 'Investigación guardada · actualiza los datos',
    filled: 'Completada', failed: 'Fallida', expired: 'Caducada', cancelled: 'Cancelada', pending: 'Pendiente de ejecución', confirming: 'Verificando liquidación', buy: 'Comprar', sell: 'Vender', estimated: 'Recepción estimada', received: 'Recibido', missing: 'Cantidad no disponible' },
  fr: { history: 'Historique', conversations: 'Conversations', orders: 'Ordres du portefeuille', empty: 'Vos conversations apparaîtront ici.', noOrders: 'Ce portefeuille n’a pas encore d’ordres.', saved: 'Enregistré sur cet appareil. Chaque portefeuille a son historique.', unsaved: 'Impossible d’enregistrer l’historique sur cet appareil.', remove: 'Supprimer la conversation', current: 'Conversation actuelle',
    auditConsent: 'Je comprends que Binance ne fournit aucun audit de sécurité pour ce jeton. J’ai vérifié le contrat et l’échange.', refreshed: 'Actualiser la recherche', savedResearch: 'Recherche enregistrée · actualisez les données',
    filled: 'Exécuté', failed: 'Échoué', expired: 'Expiré', cancelled: 'Annulé', pending: 'En attente d’exécution', confirming: 'Vérification du règlement', buy: 'Acheter', sell: 'Vendre', estimated: 'Réception estimée', received: 'Reçu', missing: 'Quantité indisponible' },
  pt: { history: 'Histórico', conversations: 'Conversas', orders: 'Ordens da carteira', empty: 'Suas conversas aparecerão aqui.', noOrders: 'Esta carteira ainda não tem ordens.', saved: 'Salvo neste dispositivo. Cada carteira tem seu histórico.', unsaved: 'Não foi possível salvar o histórico neste dispositivo.', remove: 'Excluir conversa', current: 'Conversa atual',
    auditConsent: 'Entendo que a Binance não tem uma auditoria de segurança para este token. Revisei o contrato e a negociação.', refreshed: 'Atualizar pesquisa', savedResearch: 'Pesquisa salva · atualize os dados',
    filled: 'Executada', failed: 'Falhou', expired: 'Expirada', cancelled: 'Cancelada', pending: 'Aguardando execução', confirming: 'Verificando liquidação', buy: 'Comprar', sell: 'Vender', estimated: 'Recebimento estimado', received: 'Recebido', missing: 'Valor indisponível' },
} satisfies Record<Language, object>
